name: test

on:
  push:
    branches:
      - **
    paths:
        - '**.py'

  pull_request:
    branches:
        - '**'
    paths:
        - '**.py'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install requriements.txt

      - name: Run Test
        run: |
          cd src
          python -m MaaDebugger --CI
